version: '3'
services:
    rabbitmq:
      container_name: rm-rabbitmq
      image: rabbitmq:3.7-management
      ports:
        - "15672:15672"
        - "5672:5672"
      networks:
        - kwnet
    mysql:
      container_name: rm-mysql
      image: mysql:5.7
      ports:
        - "3306:3306"
      networks:
       - kwnet
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - dbdata:/var/lib/mysql
        - logvolume01:/var/log
    rundeck:
      container_name: rm-rundeck
      image: jacekkow/rundeck
      ports:
        - "4440:4440"
      networks:
        - kwnet
volumes:
  logvolume01: {}
  dbdata: {}
networks:
  kwnet:
    driver: bridge